### ISSUE TITLE
Suggestion: Server Configurations

### ISSUE THREAD

**Issue by RChesterton** [r0ute/startup-company-calculator#12]
Thanks for creating this, it's a life-saver!

Would it be possible to include the various Server Configurations (i.e a Small Web Server takes 2x Firewall, 2x Virtual Hardware and 2x Operating System to Configure).

While the Small ones are simple enough, when it comes to the more powerful ones (i.e. XServers), it gets  pretty complicated.

It would be great to be able to work out the various staff ratios and items needed for this stuff!

Thanks!

**Comment by r0ute** [comment]
It seems it should be doable as the game.js has rack device requirements
` WebserverSmall: { name: RackDeviceNames.WebserverSmall, units: 1, price: 1e4, clockRate: 100, power: 2500, producedHeat: 8, webserverThroughput: 200, requirements: { Firewall: 2, VirtualHardware: 2, OperatingSystem: 2 } },`

Thinking about how it can be implemented:
1. You start with selecting which device type(s) you'd like to configure (e.g. WebserverSmall, CacheMedium)
2. Then you specify how many devices you want (e.g. 1 x WebserverSmall, 2 x CacheMedium )
3. Finally the app shows you how many components you need (Firewall: X, VirtualHardware: Y, etc.)

**Comment by RChesterton** [comment]
Thank you! I really appreciate this :)
